server:
  applicationConnectors:
    - type: http
      port: 8080
      maxResponseHeaderSize: 128KiB
  requestLog:
    timeZone: UTC
    appenders:
      - type: console


logging:
  level: INFO
  loggers:
      com.sample.service: INFO
      org.skife.jdbi.v2: INFO
      org.hibernate: INFO
  appenders:
    - type: console
      logFormat: "%-6level [%d{yyyy-MM-dd'T'HH:mm:ssXXX}] [%t] %logger{5} - %X{code} %msg %n"

# Database settings.
sampleDataBase:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password: password
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/FirstAPIDB

    properties:
     charSet: UTF-8
     hibernate.dialect: org.hibernate.dialect.MySQLDialect
     hibernate.show_sql: false

swagger:
  resourcePackage: com.sample.service.api
  swaggerViewConfiguration:
    templateUrl: /config/swg-index.ftl